# Generated by Django 5.2.1 on 2025-05-10 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_github_link_profile_homepage_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='homepage_link',
        ),
        migrations.AddField(
            model_name='khabar',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='khabar_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
